name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # změň na master, pokud je to tvá hlavní větev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: FirebaseExtended/action-hosting-deploy@v1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          projectId: "YOUR_FIREBASE_PROJECT_ID"
          channelId: "live"
